### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by derekbit**
https://github.com/longhorn/longhorn/issues/8394

- Fix major memory leak caused by https://github.com/nfs-ganesha/nfs-ganesha/issues/1105
- Fix minor memory leak in error handling of longhorn recovery backend.

### CODE REVIEW

**Comment by james-munson** [comment]
LGTM.  Good find in the Longhorn code.
Could we maybe split the upstream patch and the longhorn-specific fix into two separate commits?  That would make life simpler when we sync to a upstream release that has the patch.

**Comment by derekbit** [comment]
> LGTM. Good find in the Longhorn code. Could we maybe split the upstream patch and the longhorn-specific fix into two separate commits? That would make life simpler when we sync to a upstream release that has the patch.

They are already in [different commits](https://github.com/longhorn/nfs-ganesha/pull/13/commits) but in one PR. I think this is fine. WDYT?

**Review by PhanLe1010 — APPROVED** [review]
LGTM

I am a bit curious how did you figure out the Longhorn leak?

Is it because the user mentioned that have a lot of mount/umount operation which is related to our Longhorn logic to make calls to recovery backend?

**Comment by derekbit** [comment]
> LGTM
> 
> I am a bit curious how did you figure out the Longhorn leak?
> 
> Is it because the user mentioned that have a lot of mount/umount operation which is related to our Longhorn logic to make calls to recovery backend?

@PhanLe1010 
The community user found it. The case is not easy to find out, because the leak only happens when there are tons of NFS client mount and unmount operations.

**Comment by PhanLe1010** [comment]
I mean this Longhorn leak founded by you @derekbit https://github.com/longhorn/nfs-ganesha/pull/13/commits/223182bdaa8acd1b3c4813979bf3dc844f83148f

**Comment by derekbit** [comment]
> I mean this Longhorn leak founded by you @derekbit [223182b](https://github.com/longhorn/nfs-ganesha/commit/223182bdaa8acd1b3c4813979bf3dc844f83148f)

Oh! I just reviewed the backend codes again and found the (potential) leaks.
These leaks should be very minor and not easy to find in a runtime environment.

**Comment by james-munson** [comment]
Sorry for the delay getting back to this.  That looks good.

**Pull request merged**
