### PR TITLE
Longhorn ganesha v5 fix hang

### PR DESCRIPTION
**Pull request by derekbit**
https://github.com/longhorn/longhorn/issues/8253

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by PhanLe1010** [comment]
I think we need to be careful because we are cherry picking from upstream PRs but the upstream fixed PRs have not been merged:
1. https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1188187
2. https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1188188

 They are actively reviewing it so maybe better to wait for them to merge first before we add this to our stable releases. Hope that they will merge in the next few days though.

**Comment by innobead** [comment]
Agreed with you. Let's don't update the share manager first even though this PR has been merged.

The current temp patch is more for unblocking the testing only.

**Comment by derekbit** [comment]
Yes, merged too fast ^^".
According to the conversation, it is almost there! Let's revert them and apply the final patches later.

**Comment by innobead** [comment]
From @derekbit info, the upstream merged the fix.

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1188187
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1188188

**Pull request merged**
